-- HR 스키마 삭제 
DROP TABLE JOB_HISTORY CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEES   CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENTS CASCADE CONSTRAINTS;
DROP TABLE LOCATIONS   CASCADE CONSTRAINTS;
DROP TABLE COUNTRIES   CASCADE CONSTRAINTS;
DROP TABLE REGIONS     CASCADE CONSTRAINTS;
DROP TABLE JOBS        CASCADE CONSTRAINTS;